# Generated by Django 3.2.14 on 2022-07-19 11:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='chapter title')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='ourse_title')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('lesson_type', models.CharField(max_length=20, verbose_name='lesson type')),
                ('duration', models.PositiveIntegerField(verbose_name='duration')),
            ],
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapter_in_course', to='api.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='api.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.ManyToManyField(through='api.CourseChapter', to='api.Chapter'),
        ),
        migrations.CreateModel(
            name='ChapterLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='lessons number in chapter')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapter', to='api.chapter')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_in_chapter', to='api.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='lesson',
            field=models.ManyToManyField(through='api.ChapterLesson', to='api.Lesson'),
        ),
        migrations.AddConstraint(
            model_name='coursechapter',
            constraint=models.UniqueConstraint(fields=('course', 'chapter'), name='unique_chapter_in_course'),
        ),
        migrations.AddConstraint(
            model_name='chapterlesson',
            constraint=models.UniqueConstraint(fields=('chapter', 'lesson', 'lesson_order'), name='unique_lesson_in_chapter'),
        ),
    ]
